// Field types supported by the generic form renderer (AdminForm.jsx):
// text, textarea, number, date, checkbox, select, media, stringList (one item per line -> array of strings)

export const resources = {
  'hero-slides': {
    label: 'Hero Slides',
    endpoint: '/hero-slides',
    resourceKey: 'content',
    columns: [{ key: 'title', label: 'Title' }, { key: 'dateLabel', label: 'Date' }, { key: 'isActive', label: 'Active' }],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'dateLabel', label: 'Date label', type: 'text', placeholder: '31 AUG' },
      { name: 'venueLabel', label: 'Venue label', type: 'text' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  stats: {
    label: 'Stats',
    endpoint: '/stats',
    resourceKey: 'content',
    columns: [{ key: 'value', label: 'Value' }, { key: 'label', label: 'Label' }],
    fields: [
      { name: 'value', label: 'Value', type: 'text', required: true, placeholder: '450+' },
      { name: 'label', label: 'Label', type: 'text', required: true, placeholder: 'Creators Attended' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  sponsors: {
    label: 'Sponsors',
    endpoint: '/sponsors',
    resourceKey: 'content',
    columns: [{ key: 'name', label: 'Name' }, { key: 'tier', label: 'Tier' }, { key: 'isActive', label: 'Active' }],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'websiteUrl', label: 'Website URL', type: 'text' },
      {
        name: 'tier',
        label: 'Tier',
        type: 'select',
        options: ['title', 'platinum', 'gold', 'silver', 'partner', 'media_partner'],
      },
      { name: 'logo', label: 'Logo', type: 'media' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  competitions: {
    label: 'Competitions',
    endpoint: '/competitions',
    resourceKey: 'content',
    columns: [{ key: 'title', label: 'Title' }, { key: 'slug', label: 'Slug' }, { key: 'isActive', label: 'Active' }],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true, placeholder: 'collabverse-2025' },
      { name: 'shortDescription', label: 'Short description', type: 'textarea' },
      { name: 'body', label: 'Full page body', type: 'textarea', rows: 8 },
      { name: 'coverImage', label: 'Cover image', type: 'media' },
      { name: 'registerUrl', label: 'Register URL', type: 'text' },
      { name: 'rules', label: 'Rules (one per line)', type: 'stringList' },
      { name: 'prizeSummary', label: 'Prize summary', type: 'text' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  workshops: {
    label: 'Workshops',
    endpoint: '/workshops',
    resourceKey: 'content',
    columns: [{ key: 'title', label: 'Title' }, { key: 'facilitatorName', label: 'Facilitator' }],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'facilitatorName', label: 'Facilitator', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'coverImage', label: 'Cover image', type: 'media' },
      { name: 'timeSlot', label: 'Time slot', type: 'text' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  awards: {
    label: 'Award Categories',
    endpoint: '/awards',
    resourceKey: 'content',
    columns: [{ key: 'title', label: 'Title' }, { key: 'year', label: 'Year' }, { key: 'winnerName', label: 'Winner' }],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'year', label: 'Year', type: 'number', required: true },
      { name: 'winnerName', label: 'Winner name', type: 'text' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  activities: {
    label: 'Activities',
    endpoint: '/activities',
    resourceKey: 'content',
    columns: [{ key: 'title', label: 'Title' }],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'coverImage', label: 'Cover image', type: 'media' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  testimonials: {
    label: 'Testimonials',
    endpoint: '/testimonials',
    resourceKey: 'content',
    columns: [{ key: 'handle', label: 'Handle' }, { key: 'quote', label: 'Quote' }, { key: 'year', label: 'Year' }],
    fields: [
      { name: 'handle', label: 'Instagram handle', type: 'text', required: true, placeholder: '@handle' },
      { name: 'displayName', label: 'Display name', type: 'text' },
      { name: 'quote', label: 'Quote', type: 'textarea', required: true },
      { name: 'avatarOrClip', label: 'Avatar / clip', type: 'media' },
      { name: 'year', label: 'Year', type: 'number' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  tickets: {
    label: 'Tickets',
    endpoint: '/tickets',
    resourceKey: 'content',
    columns: [
      { key: 'label', label: 'Label' },
      { key: 'price', label: 'Price' },
      { key: 'status', label: 'Status' },
      { key: 'soldCount', label: 'Sold' },
    ],
    fields: [
      { name: 'label', label: 'Label', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'eventDate', label: 'Event date', type: 'date' },
      { name: 'price', label: 'Price (INR)', type: 'number', required: true },
      { name: 'originalPrice', label: 'Original price (for strike-through)', type: 'number' },
      { name: 'totalStock', label: 'Total stock (blank = unlimited)', type: 'number' },
      { name: 'salesStartAt', label: 'Sales start', type: 'date' },
      { name: 'salesEndAt', label: 'Sales end', type: 'date' },
      { name: 'status', label: 'Status', type: 'select', options: ['upcoming', 'available', 'sold-out', 'closed'] },
      { name: 'order', label: 'Order', type: 'number' },
    ],
    reorderable: true,
  },
  agenda: {
    label: 'Agenda',
    endpoint: '/agenda',
    resourceKey: 'content',
    columns: [{ key: 'title', label: 'Title' }, { key: 'timeLabel', label: 'Time' }],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'timeLabel', label: 'Time label', type: 'text', required: true, placeholder: '11:00 AM – 2:00 PM' },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'subItems', label: 'Sub-items (one per line)', type: 'stringList' },
      { name: 'year', label: 'Year', type: 'number' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  speakers: {
    label: 'Speakers & Committee',
    endpoint: '/speakers',
    resourceKey: 'content',
    columns: [{ key: 'name', label: 'Name' }, { key: 'category', label: 'Category' }, { key: 'year', label: 'Year' }],
    fields: [
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'title', label: 'Title / role', type: 'text' },
      { name: 'bio', label: 'Bio', type: 'textarea' },
      { name: 'photo', label: 'Photo', type: 'media' },
      {
        name: 'category',
        label: 'Category',
        type: 'select',
        options: ['speaker', 'committee', 'judge', 'host', 'volunteer'],
      },
      { name: 'year', label: 'Year', type: 'number' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  faqs: {
    label: 'FAQs',
    endpoint: '/faqs',
    resourceKey: 'faqs',
    columns: [{ key: 'question', label: 'Question' }, { key: 'category', label: 'Category' }],
    fields: [
      { name: 'question', label: 'Question', type: 'text', required: true },
      { name: 'answer', label: 'Answer', type: 'textarea', required: true },
      { name: 'category', label: 'Category', type: 'text', placeholder: 'general, collabverse, tickets...' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  'gallery-albums': {
    label: 'Gallery Albums',
    endpoint: '/gallery-albums',
    resourceKey: 'gallery',
    columns: [{ key: 'title', label: 'Title' }, { key: 'year', label: 'Year' }],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, placeholder: '2024 Highlights' },
      { name: 'year', label: 'Year', type: 'number', required: true },
      { name: 'description', label: 'Description', type: 'textarea' },
      { name: 'coverImage', label: 'Cover image', type: 'media' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
    reorderable: true,
  },
  notices: {
    label: 'Notices & Announcements',
    endpoint: '/notices',
    resourceKey: 'content',
    columns: [{ key: 'title', label: 'Title' }, { key: 'type', label: 'Type' }, { key: 'isActive', label: 'Active' }],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'body', label: 'Body', type: 'textarea' },
      { name: 'type', label: 'Type', type: 'select', options: ['notice', 'marquee', 'news'] },
      { name: 'expiresAt', label: 'Expires at', type: 'date' },
      { name: 'order', label: 'Order', type: 'number' },
      { name: 'isActive', label: 'Active', type: 'checkbox' },
    ],
  },
  blogs: {
    label: 'Blog Posts',
    endpoint: '/blogs',
    resourceKey: 'content',
    columns: [{ key: 'title', label: 'Title' }, { key: 'status', label: 'Status' }],
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true },
      { name: 'slug', label: 'Slug', type: 'text', required: true },
      { name: 'excerpt', label: 'Excerpt', type: 'textarea' },
      { name: 'body', label: 'Body', type: 'textarea', rows: 10 },
      { name: 'coverImage', label: 'Cover image', type: 'media' },
      { name: 'status', label: 'Status', type: 'select', options: ['draft', 'published'] },
    ],
  },
};

export const resourceOrder = [
  'hero-slides',
  'stats',
  'sponsors',
  'competitions',
  'workshops',
  'awards',
  'activities',
  'testimonials',
  'tickets',
  'agenda',
  'speakers',
  'faqs',
  'gallery-albums',
  'notices',
  'blogs',
];
